config/routes.rb
Rails.application.routes.draw do
  resources :cart_items, only: [:create] do
    collection do
      post :remove
    end
  end
  resources :addons, only: [:create, :destroy]
  resources :variations, only: [:create, :destroy]
  resources :foods, only: [:create, :destroy]
  resources :carts, only: [:create, :destroy] do
    collection do
      get :details
    end
  end
  resources :users, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/variation.rb
class Variation < ApplicationRecord
  validates :name, presence: true, allow_nil: false
  validates :price, numericality: { greater_than: 0 }, presence: true
  belongs_to :food
end

app/controllers/variations_controller.rb
class VariationsController < ApplicationController
  before_action :set_variation, only: %i[destroy]

  # POST /variations or /variations.json
  def create
    @variation = Variation.new(variation_params)

    if @variation.save
      render { msg: ["Variation was successfully created."] }, status: 200
    else
      render json: { msg: @variation.errors }, status: 401
    end
  end

  # DELETE /variations/1 or /variations/1.json
  def destroy
    @variation.destroy

    render json: { msg: "Variation was successfully destroyed." }, status: 200    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_variation
      @variation = Variation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def variation_params
      params.fetch(:variation, {:food_id, :name, :price, :description})
    end
end

app/helpers/variations_helper.rb
module VariationsHelper
end

app/views/variations/_form.html.erb
<%= form_with(model: variation, local: true) do |form| %>
  <% if variation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(variation.errors.count, "error") %> prohibited this variation from being saved:</h2>

      <ul>
        <% variation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/variations/edit.html.erb
<h1>Editing Variation</h1>

<%= render 'form', variation: @variation %>

<%= link_to 'Show', @variation %> |
<%= link_to 'Back', variations_path %>

app/views/variations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Variations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @variations.each do |variation| %>
      <tr>
        <td><%= link_to 'Show', variation %></td>
        <td><%= link_to 'Edit', edit_variation_path(variation) %></td>
        <td><%= link_to 'Destroy', variation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Variation', new_variation_path %>

app/views/variations/new.html.erb
<h1>New Variation</h1>

<%= render 'form', variation: @variation %>

<%= link_to 'Back', variations_path %>

app/views/variations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_variation_path(@variation) %> |
<%= link_to 'Back', variations_path %>